# Using atp.kubernetes.io/path  Annotation
# We are setting atp.kubernetes.io/path  to tell the plugin exactly where to find data
# https://argocd-terraform-plugin.readthedocs.io/en/stable/howitworks/#generic-placeholders
kind: Secret
apiVersion: v1
metadata:
  name: example-annotation
  annotations:
    atp.kubernetes.io/path: "env/test1/terraform.tfstate"
type: Opaque
data:
  username: <terraform:string_value>
  password: <password>
