# Using inline-path placeholders
# This creates the same data as annotation-example.yaml but without the annotation
# https://argocd-vault-plugin.readthedocs.io/en/stable/howitworks/#inline-path-placeholders
kind: Secret
apiVersion: v1
metadata:
  name: example-annotation
type: Opaque
stringData:
  username: <terraform:path:env/test1/terraform.tfstate#int_value>
  password: <terraform:path:env/test1/terraform.tfstate#string_value>
