apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
      - name: argocd-repo-server
        volumeMounts:
        - name: custom-tools
          mountPath: /usr/local/bin/argocd-terraform-plugin
          subPath: argocd-terraform-plugin

        # Note: ATP config (for the secret manager, etc) can be passed in several ways. This is just one example
        # https://argocd-terraform-plugin.readthedocs.io/en/stable/config/
        envFrom:
          - secretRef:
              name: argocd-terraform-plugin-credentials
      volumes:
      - name: custom-tools
        emptyDir: {}
      initContainers:
      - name: download-tools
        image: alpine:3.8
        command: [sh, -c]

        # Don't forget to update this to whatever the stable release version is
        # Note the lack of the `v` prefix unlike the git tag
        env:
          - name: ATP_VERSION
            value: "1.7.0"
        args:
          - >-
            wget -O argocd-terraform-plugin
            https://github.com/KazanExpress/argocd-terraform-plugin/releases/download/v${ATP_VERSION}/argocd-terraform-plugin_${ATP_VERSION}_linux_amd64 &&
            chmod +x argocd-terraform-plugin &&
            mv argocd-terraform-plugin /custom-tools/
        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools

      # Not strictly necessary, but required for passing ATP configuration from a secret and for using Kubernetes auth to Hashicorp Vault
      automountServiceAccountToken: true
